### ISSUE TITLE
how to build?

### ISSUE THREAD

**Issue by uzunenx** [lihaochen910/GamePrototype#1]
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0234	The type or namespace name 'Utility' does not exist in the namespace 'DigitalRune' (are you missing an assembly reference?)	Pixpil.GamePrototype.Editor	C:\GamePrototype\
src\Pixpil.GamePrototype.Editor\CustomEditors\GoapScenarioAssetEditor.cs	7	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0103	The name 'ReflectionHelper' does not exist in the current context	Pixpil.GamePrototype.Editor	C:\GamePrototype\src\Pixpil.GamePrototype.Editor\CustomEditors\GoapScenarioAssetEditor.cs	33	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'int' does not contain a definition for 'Times' and no accessible extension method 'Times' accepting a first argument of type 'int' could be found (are you missing a using directive or an assembly reference?)	Pixpil.GamePrototype.Editor	C:\GamePrototype\src\Pixpil.GamePrototype.Editor\CustomEditors\GoapScenarioAssetEditor.cs	221	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS0122	'Prettify' is inaccessible due to its protection level	Pixpil.GamePrototype.Editor	C:\GamePrototype\src\Pixpil.GamePrototype.Editor\CustomEditors\UtilityAiAssetEditor.cs	146	Active
Severity	Code	Description	Project	File	Line	Suppression State
Error	CS1061	'Map' does not contain a definition for 'UnSetOccupiedAsStatic' and no accessible extension method 'UnSetOccupiedAsStatic' accepting a first argument of type 'Map' could be found (are you missing a using directive or an assembly reference?)	Pixpil.GamePrototype	C:\GamePrototype\src\Pixpil.GamePrototype\Systems\DarkFog\DarkFogSystem.cs	203	Active

**Comment by lihaochen910** [comment]
[DigitalRune.zip](https://github.com/lihaochen910/GamePrototype/files/15089921/DigitalRune.zip)
And
Murder/Core/Grid/Map.cs
```csharp
public void UnSetOccupiedAsStatic(int x, int y, int layer)
{
    _gridMap[(y * Width) + x].CollisionType &= layer;
}
```

**Comment by uzunenx** [comment]
everything works but it crashes when creating a UtilityAiAsset
```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=Pixpil.GamePrototype.Editor
  StackTrace:
   at Pixpil.GamePrototype.Editor.CustomEditors.UtilityAiAssetEditor.DrawEditor() in C:\GamePrototype\src\Pixpil.GamePrototype.Editor\CustomEditors\UtilityAiAssetEditor.cs:line 146
```

**Comment by lihaochen910** [comment]
> everything works but it crashes when creating a UtilityAiAsset
> 
> ```
> System.NullReferenceException
>   HResult=0x80004003
>   Message=Object reference not set to an instance of an object.
>   Source=Pixpil.GamePrototype.Editor
>   StackTrace:
>    at Pixpil.GamePrototype.Editor.CustomEditors.UtilityAiAssetEditor.DrawEditor() in C:\GamePrototype\src\Pixpil.GamePrototype.Editor\CustomEditors\UtilityAiAssetEditor.cs:line 146
> ```

fixed.

**Comment by uzunenx** [comment]
cant seem to create new prefabs with these components

InventoryComponent
BuildingConstructRequireResourcesComponent
BuildingWorkersInConstructingComponent
BuildingWorkersInWorkingComponent
DormitoryPersonnelSituationComponent

```
{ [21:46:43] Initialize (line 55): Exception was thrown! This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property. }
{    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state) }
{ [21:46:43] DrawSelectedAsset (line 155): Sorry, I was unable to save asset: dormitry :( }

System.InvalidOperationException
  HResult=0x80131509
  Message=This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
  Source=System.Text.Json
```

**Comment by lihaochen910** [comment]
> cant seem to create new prefabs with these components
> 
> InventoryComponent BuildingConstructRequireResourcesComponent BuildingWorkersInConstructingComponent BuildingWorkersInWorkingComponent DormitoryPersonnelSituationComponent
> 
> ```
> { [21:46:43] Initialize (line 55): Exception was thrown! This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property. }
> {    at System.Text.Json.Serialization.Converters.IEnumerableDefaultConverter`2.OnWriteResume(Utf8JsonWriter writer, TCollection value, JsonSerializerOptions options, WriteStack& state) }
> { [21:46:43] DrawSelectedAsset (line 155): Sorry, I was unable to save asset: dormitry :( }
> 
> System.InvalidOperationException
>   HResult=0x80131509
>   Message=This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
>   Source=System.Text.Json
> ```

murder/src/Murder.Editor/CustomEditors/AssetEditor.cs(line:385)
```csharp
// TODO: This is modifying the memory of all readonly structs.
IComponent copy = default;
try
{
    copy = SerializationHelper.DeepCopy(c);
}
catch (InvalidOperationException)
{
    copy = c;
}

if (CustomComponent.ShowEditorOf(ref copy))
{
    // Asset was already modified, just pass along the updated asset.
    ReplaceComponent(parent, entityInstance, (IComponent)copy);
}
```

**Comment by uzunenx** [comment]
still get the same error with these components but on a different line
BuildingWorkersInConstructingComponent
BuildingWorkersInWorkingComponent
DormitoryPersonnelSituationComponent

on this line
murder/src/Murder.Editor/CustomEditors/ImmutableArrayIntField.cs(line:21)
```csharp
var cache = String.Join(',', current);
```

**Comment by lihaochen910** [comment]
> still get the same error with these components but on a different line BuildingWorkersInConstructingComponent BuildingWorkersInWorkingComponent DormitoryPersonnelSituationComponent
> 
> on this line murder/src/Murder.Editor/CustomEditors/ImmutableArrayIntField.cs(line:21)
> 
> ```cs
> var cache = String.Join(',', current);
> ```

Pull the latest commit

**Comment by uzunenx** [comment]
i pulled latest but still get the same error on line 21

```
System.InvalidOperationException
  HResult=0x80131509
  Message=This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
  Source=System.Collections.Immutable
  StackTrace:
   at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
   at System.String.Join[T](Char separator, IEnumerable`1 values)
   at Murder.Editor.CustomFields.ImmutableArrayIntField.ProcessInput(EditorMember member, Object fieldValue) in C:\GamePrototype\murder\src\Murder.Editor\CustomFields\ImmutableArrayIntField.cs:line 21
   at Murder.Editor.CustomFields.CustomField.DrawValue(EditorMember member, Object value) in C:\GamePrototype\murder\src\Murder.Editor\CustomFields\CustomField.cs:line 83
   at Murder.Editor.CustomComponents.CustomComponent.<>c__DisplayClass10_0.<DrawMember>b__0() in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 269
   at Murder.Editor.CustomComponents.CustomComponent.ProcessInput(Object target, EditorMember member, Func`1 inputAction) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 294
   at Murder.Editor.CustomComponents.CustomComponent.DrawMember(Object target, Boolean& fileChanged, EditorMember member) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 269
   at Murder.Editor.CustomComponents.CustomComponent.DrawMemberForTarget(Object target, String memberName, EditorMember member) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 259
   at Murder.Editor.CustomComponents.CustomComponent.DrawMembersForTarget(Object target, IList`1 members, String filter) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 230
   at Murder.Editor.CustomComponents.CustomComponent.DrawAllMembersWithTable(Object& target, Boolean sameLineFilter) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 145
   at Murder.Editor.CustomComponents.CustomComponent.ShowEditorOf[T](T& target, CustomComponentsFlags flags) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 36
   at Murder.Editor.CustomEditors.AssetEditor.DrawEntityContent(IEntity entityInstance, Boolean canBeCollapsed, IEntity parent) in C:\GamePrototype\murder\src\Murder.Editor\CustomEditors\AssetEditor.cs:line 396
   at Murder.Editor.CustomEditors.AssetEditor.DrawEntity(IEntity entityInstance, Boolean canBeColapsed, IEntity parent) in C:\GamePrototype\murder\src\Murder.Editor\CustomEditors\AssetEditor.cs:line 182
   at Murder.Editor.CustomEditors.PrefabAssetEditor.DrawEditor() in C:\GamePrototype\murder\src\Murder.Editor\CustomEditors\PrefabAssetEditor.cs:line 62
   at Murder.Editor.EditorScene.DrawSelectedAsset(GameAsset asset) in C:\GamePrototype\murder\src\Murder.Editor\EditorScene_Editors.cs:line 265
   at Murder.Editor.EditorScene.DrawAssetEditors() in C:\GamePrototype\murder\src\Murder.Editor\EditorScene_Editors.cs:line 91
   at Murder.Editor.EditorScene.DrawGui() in C:\GamePrototype\murder\src\Murder.Editor\EditorScene.cs:line 219
   at Murder.Editor.Architect.DrawImGui(GameTime gameTime) in C:\GamePrototype\murder\src\Murder.Editor\Architect.cs:line 348
   at Murder.Game.Draw(GameTime gameTime) in C:\GamePrototype\murder\src\Murder\Game.cs:line 808
   at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Pixpil.Editor.Program.Main() in C:\GamePrototype\src\Pixpil.GamePrototype.Editor\Program.cs:line 14
```

**Comment by lihaochen910** [comment]
> i pulled latest but still get the same error on line 21
> 
> ```
> System.InvalidOperationException
>   HResult=0x80131509
>   Message=This operation cannot be performed on a default instance of ImmutableArray<T>.  Consider initializing the array, or checking the ImmutableArray<T>.IsDefault property.
>   Source=System.Collections.Immutable
>   StackTrace:
>    at System.Collections.Immutable.ImmutableArray`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
>    at System.String.JoinCore[T](ReadOnlySpan`1 separator, IEnumerable`1 values)
>    at System.String.Join[T](Char separator, IEnumerable`1 values)
>    at Murder.Editor.CustomFields.ImmutableArrayIntField.ProcessInput(EditorMember member, Object fieldValue) in C:\GamePrototype\murder\src\Murder.Editor\CustomFields\ImmutableArrayIntField.cs:line 21
>    at Murder.Editor.CustomFields.CustomField.DrawValue(EditorMember member, Object value) in C:\GamePrototype\murder\src\Murder.Editor\CustomFields\CustomField.cs:line 83
>    at Murder.Editor.CustomComponents.CustomComponent.<>c__DisplayClass10_0.<DrawMember>b__0() in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 269
>    at Murder.Editor.CustomComponents.CustomComponent.ProcessInput(Object target, EditorMember member, Func`1 inputAction) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 294
>    at Murder.Editor.CustomComponents.CustomComponent.DrawMember(Object target, Boolean& fileChanged, EditorMember member) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 269
>    at Murder.Editor.CustomComponents.CustomComponent.DrawMemberForTarget(Object target, String memberName, EditorMember member) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 259
>    at Murder.Editor.CustomComponents.CustomComponent.DrawMembersForTarget(Object target, IList`1 members, String filter) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 230
>    at Murder.Editor.CustomComponents.CustomComponent.DrawAllMembersWithTable(Object& target, Boolean sameLineFilter) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 145
>    at Murder.Editor.CustomComponents.CustomComponent.ShowEditorOf[T](T& target, CustomComponentsFlags flags) in C:\GamePrototype\murder\src\Murder.Editor\CustomComponents\CustomComponent.cs:line 36
>    at Murder.Editor.CustomEditors.AssetEditor.DrawEntityContent(IEntity entityInstance, Boolean canBeCollapsed, IEntity parent) in C:\GamePrototype\murder\src\Murder.Editor\CustomEditors\AssetEditor.cs:line 396
>    at Murder.Editor.CustomEditors.AssetEditor.DrawEntity(IEntity entityInstance, Boolean canBeColapsed, IEntity parent) in C:\GamePrototype\murder\src\Murder.Editor\CustomEditors\AssetEditor.cs:line 182
>    at Murder.Editor.CustomEditors.PrefabAssetEditor.DrawEditor() in C:\GamePrototype\murder\src\Murder.Editor\CustomEditors\PrefabAssetEditor.cs:line 62
>    at Murder.Editor.EditorScene.DrawSelectedAsset(GameAsset asset) in C:\GamePrototype\murder\src\Murder.Editor\EditorScene_Editors.cs:line 265
>    at Murder.Editor.EditorScene.DrawAssetEditors() in C:\GamePrototype\murder\src\Murder.Editor\EditorScene_Editors.cs:line 91
>    at Murder.Editor.EditorScene.DrawGui() in C:\GamePrototype\murder\src\Murder.Editor\EditorScene.cs:line 219
>    at Murder.Editor.Architect.DrawImGui(GameTime gameTime) in C:\GamePrototype\murder\src\Murder.Editor\Architect.cs:line 348
>    at Murder.Game.Draw(GameTime gameTime) in C:\GamePrototype\murder\src\Murder\Game.cs:line 808
>    at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.Tick()
>    at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
>    at Pixpil.Editor.Program.Main() in C:\GamePrototype\src\Pixpil.GamePrototype.Editor\Program.cs:line 14
> ```
src/Murder.Editor/CustomFields/ImmutableArrayIntField.cs(line:13)
```csharp
if (current.IsDefault)
{
    current = ImmutableArray.CreateBuilder<int>().ToImmutableArray();
    return (true, current);
}
```

**Comment by uzunenx** [comment]
thanks for all the help
i cant actually load the game

these systems cause an error when enabled

DormitoryWorkerSpawnSystem
SpawnPlayerOnGameBegin

```
System.ArgumentException
  HResult=0x80070057
  Message=Unable to find the asset of type LibraryAsset with id: 00000000-0000-0000-0000-000000000000 in database.
  Source=Murder
  StackTrace:
   at Murder.Data.GameDataManager.GetAsset[T](Guid id) in C:\GamePrototype\murder\src\Murder\Data\GameDataManager.cs:line 867
   at Pixpil.Services.LibraryServices.GetLibrary() in C:\GamePrototype\src\Pixpil.GamePrototype\Services\LibraryServices.cs:line 10
   at Pixpil.Systems.SpawnPlayerOnGameBegin.Start(Context context) in C:\GamePrototype\src\Pixpil.GamePrototype\Systems\Player\SpawnPlayerOnGameBegin.cs:line 17
   at Bang.World.Start() in C:\GamePrototype\murder\bang\src\Bang\World.cs:line 992
   at Murder.Core.Scene.Start() in C:\GamePrototype\murder\src\Murder\Core\Scenes\Scene.cs:line 127
   at Murder.Core.Scene.Update() in C:\GamePrototype\murder\src\Murder\Core\Scenes\Scene.cs:line 135
   at Murder.Game.UpdateInputAndScene() in C:\GamePrototype\murder\src\Murder\Game.cs:line 789
   at Murder.Game.UpdateImpl(GameTime gameTime) in C:\GamePrototype\murder\src\Murder\Game.cs:line 733
   at Murder.Game.Update(GameTime gameTime) in C:\GamePrototype\murder\src\Murder\Game.cs:line 663
   at Murder.Editor.Architect.Update(GameTime gameTime) in C:\GamePrototype\murder\src\Murder.Editor\Architect.cs:line 519
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at Pixpil.Editor.Program.Main() in C:\GamePrototype\src\Pixpil.GamePrototype.Editor\Program.cs:line 14
```

**Comment by lihaochen910** [comment]
> thanks for all the help i cant actually load the game
> 
> these systems cause an error when enabled
> 
> DormitoryWorkerSpawnSystem SpawnPlayerOnGameBegin
> 
> ```
> System.ArgumentException
>   HResult=0x80070057
>   Message=Unable to find the asset of type LibraryAsset with id: 00000000-0000-0000-0000-000000000000 in database.
>   Source=Murder
>   StackTrace:
>    at Murder.Data.GameDataManager.GetAsset[T](Guid id) in C:\GamePrototype\murder\src\Murder\Data\GameDataManager.cs:line 867
>    at Pixpil.Services.LibraryServices.GetLibrary() in C:\GamePrototype\src\Pixpil.GamePrototype\Services\LibraryServices.cs:line 10
>    at Pixpil.Systems.SpawnPlayerOnGameBegin.Start(Context context) in C:\GamePrototype\src\Pixpil.GamePrototype\Systems\Player\SpawnPlayerOnGameBegin.cs:line 17
>    at Bang.World.Start() in C:\GamePrototype\murder\bang\src\Bang\World.cs:line 992
>    at Murder.Core.Scene.Start() in C:\GamePrototype\murder\src\Murder\Core\Scenes\Scene.cs:line 127
>    at Murder.Core.Scene.Update() in C:\GamePrototype\murder\src\Murder\Core\Scenes\Scene.cs:line 135
>    at Murder.Game.UpdateInputAndScene() in C:\GamePrototype\murder\src\Murder\Game.cs:line 789
>    at Murder.Game.UpdateImpl(GameTime gameTime) in C:\GamePrototype\murder\src\Murder\Game.cs:line 733
>    at Murder.Game.Update(GameTime gameTime) in C:\GamePrototype\murder\src\Murder\Game.cs:line 663
>    at Murder.Editor.Architect.Update(GameTime gameTime) in C:\GamePrototype\murder\src\Murder.Editor\Architect.cs:line 519
>    at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
>    at Microsoft.Xna.Framework.Game.Tick()
>    at Microsoft.Xna.Framework.SdlGamePlatform.RunLoop()
>    at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
>    at Pixpil.Editor.Program.Main() in C:\GamePrototype\src\Pixpil.GamePrototype.Editor\Program.cs:line 14
> ```

just create LibraryAsset
<img width="688" alt="image" src="https://github.com/lihaochen910/GamePrototype/assets/11693880/0beb1bc3-9521-4712-994d-5544c4c9293e">

**Comment by uzunenx** [comment]
the LibraryAsset matches the screenshot. not sure why im getting an error
![e](https://github.com/lihaochen910/GamePrototype/assets/157023026/0aa61c0f-b56b-479e-91c2-03d7c6ec411c)
![r](https://github.com/lihaochen910/GamePrototype/assets/157023026/090c7c5d-fc3d-4e5e-882f-88eec2e15640)

**Comment by lihaochen910** [comment]
Make sure you also assign a value to GameProfile
<img width="653" alt="image" src="https://github.com/lihaochen910/GamePrototype/assets/11693880/86f67124-e5d3-424a-bf4e-06e4d06ada9e">

**Comment by enoxuzu** [comment]
i cant recreate the assets as the fields are missing in the editor
![1](https://github.com/lihaochen910/GamePrototype/assets/157023026/e4f6da55-7067-4f77-925d-de8778664b53)
![2](https://github.com/lihaochen910/GamePrototype/assets/157023026/f6fd4511-ef5a-4cf5-8b1a-05b94741d794)

![4](https://github.com/lihaochen910/GamePrototype/assets/157023026/db9445ab-601b-4648-8b2d-5964dff7e086)
![3](https://github.com/lihaochen910/GamePrototype/assets/157023026/cb74d7f1-9644-4fed-8417-101f010d8afc)

**Comment by uzunenx** [comment]
theres only two more errors

cant access the blackboard component
```
System.NotSupportedException
  HResult=0x80131515
  Message=JsonTypeInfo metadata for type 'System.Text.Json.JsonElement' was not provided by TypeInfoResolver of type 'Murder.Utilities.SerializationHelper+ModifierResolver'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically. The unsupported member type is located on type 'System.Object'. Path: $.Variables.Value.
  Source=System.Text.Json
  StackTrace:
   at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
   at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
   at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
   at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
   at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
   at Murder.Utilities.SerializationHelper.DeepCopy[T](T c) in C:\GamePrototype\murder\src\Murder\Utilities\Serialization\SerializationHelper.cs:line 29

  This exception was originally thrown at this call stack:
    [External Code]

Inner Exception 1:
NotSupportedException: JsonTypeInfo metadata for type 'System.Text.Json.JsonElement' was not provided by TypeInfoResolver of type 'Murder.Utilities.SerializationHelper+ModifierResolver'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
```

can't edit the Action & Impl tab in GoapScenarios
```
System.InvalidCastException
  HResult=0x80004002
  Message=Unable to cast object of type 'Pixpil.AI.Actions.GoapActionPhase' to type 'System.Int32'.
  Source=Murder.Editor
  StackTrace:
   at Murder.Editor.CustomFields.EnumField.ProcessInput(EditorMember member, Object fieldValue) in C:\GamePrototype\murder\src\Murder.Editor\CustomFields\EnumField.cs:line 53
```

**Comment by lihaochen910** [comment]
> theres only two more errors
> 
> cant access the blackboard component
> 
> ```
> System.NotSupportedException
>   HResult=0x80131515
>   Message=JsonTypeInfo metadata for type 'System.Text.Json.JsonElement' was not provided by TypeInfoResolver of type 'Murder.Utilities.SerializationHelper+ModifierResolver'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically. The unsupported member type is located on type 'System.Object'. Path: $.Variables.Value.
>   Source=System.Text.Json
>   StackTrace:
>    at System.Text.Json.ThrowHelper.ThrowNotSupportedException(WriteStack& state, NotSupportedException ex)
>    at System.Text.Json.Serialization.JsonConverter`1.WriteCore(Utf8JsonWriter writer, T& value, JsonSerializerOptions options, WriteStack& state)
>    at System.Text.Json.Serialization.Metadata.JsonTypeInfo`1.Serialize(Utf8JsonWriter writer, T& rootValue, Object rootValueBoxed)
>    at System.Text.Json.JsonSerializer.WriteString[TValue](TValue& value, JsonTypeInfo`1 jsonTypeInfo)
>    at System.Text.Json.JsonSerializer.Serialize[TValue](TValue value, JsonSerializerOptions options)
>    at Murder.Utilities.SerializationHelper.DeepCopy[T](T c) in C:\GamePrototype\murder\src\Murder\Utilities\Serialization\SerializationHelper.cs:line 29
> 
>   This exception was originally thrown at this call stack:
>     [External Code]
> 
> Inner Exception 1:
> NotSupportedException: JsonTypeInfo metadata for type 'System.Text.Json.JsonElement' was not provided by TypeInfoResolver of type 'Murder.Utilities.SerializationHelper+ModifierResolver'. If using source generation, ensure that all root types passed to the serializer have been annotated with 'JsonSerializableAttribute', along with any types that might be serialized polymorphically.
> ```
> 
> can't edit the Action & Impl tab in GoapScenarios
> 
> ```
> System.InvalidCastException
>   HResult=0x80004002
>   Message=Unable to cast object of type 'Pixpil.AI.Actions.GoapActionPhase' to type 'System.Int32'.
>   Source=Murder.Editor
>   StackTrace:
>    at Murder.Editor.CustomFields.EnumField.ProcessInput(EditorMember member, Object fieldValue) in C:\GamePrototype\murder\src\Murder.Editor\CustomFields\EnumField.cs:line 53
> ```

BlackboardComponent has been deprecated at present. I think BlackboardComponent is not suitable to be placed in ECS. You can remove the variables from the blackboard component and put them into specific components.

murder\src\Murder.Editor\CustomFields\EnumField.cs(line:53)
```csharp
int value = Convert.ToInt32(objValue);
```

**Comment by uzunenx** [comment]
thanks for the help
